### ISSUE TITLE
how to load local pdf

### ISSUE THREAD

**Issue by janbildsoehansen** [diniska/swiftui-pdf#6]
Hey how to load local pdf in macOS

**Comment by janbildsoehansen** [comment]
Helllooooo

**Comment by janbildsoehansen** [comment]
Helllooooo

**Comment by janbildsoehansen** [comment]
Helllooooo

**Comment by janbildsoehansen** [comment]
hallllloooooooooo

**Comment by diniska** [comment]
Oh, sorry, I have just notices your message. 
To load a local pdf, you firstly need an url containing path to that pdf. If you save your pdf to the application bundle, you can use `Bundle.main.path(forResource: , ofType: )` method to retrieve the path and then convert it to URL using `URL(fileURLWithPath:)` method.

The second step is to display the pdf using the url in SwiftUI: `PDFPageView(url: url)`

**Comment by janbildsoehansen** [comment]
hehe no worries 
nice and thanks will try it out

**Comment by janbildsoehansen** [comment]
i wanna show a pdf that are loaded from json file locally on Mac OS but I can't get it to work

**Comment by denis-canva** [comment]
Were you able to retrieve a link to a PDF that you need to show? Trying to understand where the roadblock in the process happens.

**Comment by diniska** [comment]
Were you able to retrieve a link to a PDF that you need to show? Trying to understand where the roadblock in the process happens

**Comment by janbildsoehansen** [comment]
i load the pdf with havneplan.pdf from the local json

PDFPageView(url: URL(fileURLWithPath: havneplan.pdf))


im not sure how to set it up im new to this :D

**Comment by diniska** [comment]
Well, so, I think, you need not the file name, but full path to the pdf file to initialize url. Otherwise, it won't find the file. 
Also, I'm not quite sure what "load the pdf from local json" means. Regularly pdfs stored not in jsons, but in files. Could you give me more context about that?

**Comment by janbildsoehansen** [comment]
i have my pdf files in a Resources folder that the json loads the files from local in the app 
its like the Swiftui Landmark tutorial App where you load your text, image data from the json file

**Comment by diniska** [comment]
Ah, got it.
So, I'd do something like this:

```swift
let resourceUrl = Bundle.main.resourcePath.map(URL.init(fileURLWithPath:)) // retriving the path to the resources folder
let pdfUrl = resourceUrl .appendingPathComponent("havneplan.pdf", isDirectory: false) // adding the pdf file name to the path
```

Then use this `pdfUrl` to create a view that displays pdf as shown in one of the previous comments: https://github.com/diniska/swiftui-pdf/issues/6#issuecomment-805723782

**Comment by janbildsoehansen** [comment]
in witch file do I set them..?

**Comment by diniska** [comment]
Well, it really depends on the architecture that you use. For example, you can create a function that returns this pdf URL like:

```swift
func createPDFUrl() -> URL {
    let resourceUrl = Bundle.main.resourcePath.map(URL.init(fileURLWithPath:))
    return resourceUrl .appendingPathComponent("havneplan.pdf", isDirectory: false)
}
```

and then use it as part of your SwiftUI hierarchy:

```swift
var body: some View {
    PDFPageView(url: createPDFUrl())
}
```

**Comment by janbildsoehansen** [comment]
its for Mac OS I can easily get it to work on IOS but im struggling with the Mac OS part

your recommendation don't show anything

**Comment by diniska** [comment]
I believe it can work for MacOS as it works in my application.
At what point the code above fails for you on MacOS? Does it return correct url?

**Comment by janbildsoehansen** [comment]
I can get it to show one pdf like this :
func createPDFUrl() -> URL {
        let resourceUrl = Bundle.main.resourcePath.map(URL.init(fileURLWithPath:))
        return resourceUrl!.appendingPathComponent("Agersø Havn.pdf" isDirectory: true)
    }

but then it just show one pdf on all views and
I wanna load a new pdf on each view that get loaded from the local json :

like this :

func createPDFUrl() -> URL {
        let resourceUrl = Bundle.main.resourcePath.map(URL.init(fileURLWithPath:))
        return resourceUrl!.appendingPathComponent(havneplan.pdf, isDirectory: true)
    }


but it don't show anything

**Comment by diniska** [comment]
What I see here is that it can open file `"Agersø Havn.pdf"` and can't open or find file `havneplan.pdf`. Are you sure that these are stored in the same location in the bundle resources for macOS?

**Comment by janbildsoehansen** [comment]
yaa  the diffrense is that the havneplan.pdf loads a pdf from the resource folder

and "Agersø Havn.pdf" is a pdf that get loaded from the resource folder

the resource folder are "shared" on IOS and Mac OS

**Comment by janbildsoehansen** [comment]
i hade to put .pdf at the end of each pfd string in the json to get it to work hehe

**Comment by diniska** [comment]
Does it work now?

**Comment by janbildsoehansen** [comment]
hey yea I got it to show the pdf :)

**Comment by diniska** [comment]
I'll close the issue then
